### ISSUE TITLE
Builds of new and current versions of qgis fails due recent protobuf3 updates

### ISSUE THREAD

**Issue by giandex** [SlackBuildsOrg/slackbuilds#5808]
I'm the maintainer of qgis and at the moment the build is broken in Slackware 15.0 stable due the cmake configuration of protobuf3 (strictly required by qgis).

I solved for Slackware current but nothing to do for the build in stable. I think this depends on the different versions of cmake, This issue affects also the current version of qgis available in SBo.

After starting the slackbuild script in Slackware 15, cmake returns this warning:

`CMake Warning at /usr/share/cmake-3.21/Modules/FindProtobuf.cmake:524 (message): `
`Protobuf compiler version 26.0 doesn't match library version 5.26.0   `
`Call Stack (most recent call first):     `
`CMakeLists.txt:377 (find_package) `
`            `                      
`-- Found Protobuf: /usr/lib64/libprotobuf.so;-lpthread (found version "5.26.0") `
`-- Found Protobuf: /usr/lib64/libprotobuf.so;-lpthread `

The warning doesn't stop the build, but it fails during the compilation.

Unfortunately I'm not able to patch the source because the source of qgis look for protobuf3 using the cmake configuration of this dependency in the system:
` find_package(Protobuf CONFIG)`
` find_package(Protobuf REQUIRED)`
` if(Protobuf_VERSION GREATER_EQUAL 4.23)`
`    set(Protobuf_LITE_LIBRARY protobuf::libprotobuf-lite)`
` endif()`
`    `
 `message(STATUS "Found Protobuf: ${Protobuf_LIBRARIES}") `

The context appears similar to the issue reported here: https://gitlab.kitware.com/cmake/cmake/-/issues/24847

**Comment by willysr** [comment]
See #5809 for testing

**Comment by giandex** [comment]
It's working also in my system, what a stupid: the cmake warning does not affect the build, the error happened because I forgot to pass OPENCL=no: the enabling of OPENCL support breaks the compilation in the machine where the Slackware stable is installed!

Sorry, please close the issue. Now I will test the builds against protobuf 26.1 but I hope that it will work

**Comment by willysr** [comment]
Yeah, it's all good now :)
