### ISSUE TITLE
academic/fet: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6718]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/academic/fet/fet.info#L1-L10

**Comment by aclemons** [comment]
This one is updated regularly, but upstream moves the files immediately

**Comment by aclemons** [comment]
https://www.lalescu.ro/liviu/fet/download/old/fet-6.20.0.tar.bz2

**Comment by willysr** [comment]
Ananda will fix this before next public update I guess
