### ISSUE TITLE
academic/jugglinglab: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6719]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/academic/jugglinglab/jugglinglab.info#L1-L10

**Comment by aclemons** [comment]
Sourceforge page has nothing on it now. Debian has the source, but script is a binary repack.

Only found our mirror so far:
https://slackware.uk/sbosrcarch/by-name/academic/jugglinglab/JugglingLab-0.6.2_other.tar.gz

**Comment by willysr** [comment]
i would recommend this to be removed from our repo

**Comment by willysr** [comment]
Removed by 7c4860c40e
