### ISSUE TITLE
development/WebStorm: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6720]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/development/WebStorm/WebStorm.info#L1-L10

**Comment by aclemons** [comment]
I think we should remove this package.
The maintainer is inactive.

The package is hopelessly out of date and has not been updated in 9 years since it was initially added to the repo (b9920d6f5bf3737964eaf6ac40e83a4c4ac0785d).

**Comment by willysr** [comment]
yes, i agreed

**Comment by willysr** [comment]
Removed by #27e3a2d15f
