### ISSUE TITLE
development/eclipse-platform: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6721]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/development/eclipse-platform/eclipse-platform.info#L1-L10

**Comment by aclemons** [comment]
New link: https://archive.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/eclipse-platform-4.19-linux-gtk-x86_64.tar.gz

I think we should remove this package.
The maintainer seems to be inactive.

The package is hopelessly out of date.

No reverse dependencies https://slackbuilds.org/advsearch.php?q=eclipse-platform&stype=revdep1

**Comment by willysr** [comment]
agreed

**Comment by willysr** [comment]
Removed by #a96047d79b
