### ISSUE TITLE
development/groovy: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6722]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/development/groovy/groovy.info#L1-L12

**Comment by aclemons** [comment]
New link: https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-2.4.10.zip

No updates since 2017 - fc00e54f2bc4783df9698e45d7c2ddab0ea214e0.

Seems the maintainer is also not active.

No reverse dependencies:
https://slackbuilds.org/advsearch.php?q=groovy&stype=revdep1

**Comment by willysr** [comment]
removal is suggested

**Comment by willysr** [comment]
Removed by #5dc34e2323
