### ISSUE TITLE
development/jbake: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6723]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/development/jbake/jbake.info#L1-L10

**Comment by aclemons** [comment]
New link: https://github.com/jbake-org/jbake/releases/download/v2.6.3/jbake-2.6.3-bin.zip

Seems the maintainer is not active. No reverse dependencies:

https://slackbuilds.org/advsearch.php?q=jbake&stype=revdep1

**Comment by willysr** [comment]
removal is suggested as well

**Comment by willysr** [comment]
Removed by #6271b788fe
