### ISSUE TITLE
libraries/xalan: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6726]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/libraries/xalan/xalan.info#L1-L10

**Comment by aclemons** [comment]
New link: https://archive.apache.org/dist/xml/xalan-j/binaries/xalan-j_2_7_1-bin-2jars.tar.gz

There have been two releases of xalan in the last 14 years, one in 2014 and once last year in 2023, both to fix CVEs. This package has not had a version bump however since it was added in 0048f71d8f0597fe8dad7646ec205d6701c4c89e.

https://xalan.apache.org/xalan-j/readme.html#notes_272
https://xalan.apache.org/xalan-j/readme.html#notes_latest

There are no reverse dependencies on SBo for xalan though.

**Comment by willysr** [comment]
Removed by #5f6c554d1e
