### ISSUE TITLE
development/GitEye: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6730]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/development/GitEye/GitEye.info#L1-L10

**Comment by aclemons** [comment]
https://git.slackbuilds.org/slackbuilds/log/development/GitEye?h=15.0

Unmaintained

**Comment by willysr** [comment]
Removed by #0545158265
