### ISSUE TITLE
development/power-architect: Download test failed.

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6731]
Download test failed. HTTP page not retrieved.

https://github.com/SlackBuildsOrg/slackbuilds/blob/bc9d18b502448dd277146e40e6546eac0cd8d670/development/power-architect/power-architect.info#L1-L10

**Comment by aclemons** [comment]
Moved here - https://bestofbi.com/architect-download/

I don't see downloads available for old versions anywhere.

**Comment by willysr** [comment]
Removed by #b1c1fd2be5
