### ISSUE TITLE
15.0-20240629.1: Build check

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#6944]
#  Overview

|  | package | i586 | x86_64 | notes | resolution |
| --- | --- | --- | --- | --- | --- |
|  | network/frr | :x:  | :x:  | broken by protobuf upgrade  |  |
|  | system/pcp | :x: | :ok: | fails with multiple jobs on i586 | #6961 |
  
# Notes 

## Raw list x86_64

https://github.com/SlackBuildsOrg/slackbuilds/issues/6944#issuecomment-2198007990

## Raw list i586

https://github.com/SlackBuildsOrg/slackbuilds/issues/6944#issuecomment-2198142716

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 all

**Comment by aclemons** [comment]
@sbo-bot: build libraries/ospray

**Comment by aclemons** [comment]
Ah, this is the one that needs a manual build because it needs ispc which needs llvm-17.0

**Comment by aclemons** [comment]
@sbo-bot: build i586 all

**Comment by aclemons** [comment]
@sbo-bot: build i586 system/pcp

**Comment by aclemons** [comment]
@sbo-bot: build amd64 system/pcp

**Comment by aclemons** [comment]
I could build system/pcp on i586 by forcing a single job. Seems flaky with multiple jobs. It previously built fin on 15 June:

```sh
# ls -la
total 9184
drwxr-xr-x   2 root root    4096 Jun 29 13:32 ./
drwxr-xr-x 318 root root   12288 Jun 29 13:32 ../
-rw-r--r--   1 root root    1028 Jun 15 09:22 pcp-6.0.4-i586-3_SBo.dep
-rw-r--r--   1 root root  178032 Jun 15 09:22 pcp-6.0.4-i586-3_SBo.lst
-rw-r--r--   1 root root     403 Jun 15 09:22 pcp-6.0.4-i586-3_SBo.meta
-rw-r--r--   1 root root     180 Jun 15 09:22 pcp-6.0.4-i586-3_SBo.txt
-rw-r--r--   1 root root 9180444 Jun 15 09:21 pcp-6.0.4-i586-3_SBo.txz
-rw-r--r--   1 root root      59 Jun 15 09:22 pcp-6.0.4-i586-3_SBo.txz.md5
-rw-r--r--   1 root root      91 Jun 15 09:22 pcp-6.0.4-i586-3_SBo.txz.sha256
-rw-r--r--   1 root root    1658 Jun 29 13:32 revision
```

Seems the change in one of the dependencies:

```
python/python3-openpyxl
perl/perl-Test-Needs
```

has caused something to be slightly differently ordered and to fail with multiple jobs. Should we force a single job for all or just for i?86?

**Comment by willysr** [comment]
i would go with -j1 for all arch
it's not a big package right?

**Comment by willysr** [comment]
i wonder why debugpy failed?
it built just fine in https://github.com/SlackBuildsOrg/slackbuilds/pull/6900

**Comment by willysr** [comment]
@sbo-bot: build python/python3-debugpy

**Comment by aclemons** [comment]
> i would go with -j1 for all arch it's not a big package right?

Takes about 15 minutes to build with one job

**Comment by willysr** [comment]
> > i would go with -j1 for all arch it's not a big package right?
> 
> Takes about 15 minutes to build with one job

ah, that makes a big difference, so yeah let's go with your idea to speed things up

**Comment by aclemons** [comment]
> i wonder why debugpy failed? it built just fine in #6900

Seems it was re-tagged or something. Definitely a different md5sum now

**Comment by willysr** [comment]
wait, python3-debugpy wasn't included in this batch?
i merged that PR already, but somehow it missed for this week

**Comment by willysr** [comment]
> > i wonder why debugpy failed? it built just fine in #6900
> 
> Seems it was re-tagged or something. Definitely a different md5sum now

yeah, just downloaded the new tarball and it gives different checksum from the PR as well

**Comment by aclemons** [comment]
https://github.com/SlackBuildsOrg/slackbuilds/pull/6954 will handle debugpy

**Comment by aclemons** [comment]
Complete for this week.
