### ISSUE TITLE
15.0-20240706.1: Build check

### ISSUE THREAD

**Issue by aclemons** [SlackBuildsOrg/slackbuilds#7018]
#  Overview

|  | package | i586 | x86_64 | notes | resolution |
| --- | --- | --- | --- | --- | --- |
|  | network/frr | :x:  | :x:  | broken by protobuf upgrade  |  |

# Notes 

## Raw list x86_64

https://github.com/SlackBuildsOrg/slackbuilds/issues/7018#issuecomment-2211971438

## Raw list i586

https://github.com/SlackBuildsOrg/slackbuilds/issues/7018#issuecomment-2211756104

**Comment by aclemons** [comment]
@sbo-bot: build i586 all

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 all

**Comment by aclemons** [comment]
Ok, I've set up the bot now to support "build all" on gitlab too, so we can do the weekly tracking here or there in future:

https://gitlab.com/SlackBuilds.org/slackbuilds/-/issues/4

**Comment by willysr** [comment]
nice, thanks for the work :)

**Comment by willysr** [comment]
@sbo-bot: build x86_64 development/gambas3

**Comment by willysr** [comment]
@sbo-bot: build x86_64 development/kicad
