### ISSUE TITLE
docker security vulnerability

### ISSUE THREAD

**Issue by willysr** [SlackBuildsOrg/slackbuilds#7253]
Docker in our repository is probably affected by this: https://www.docker.com/blog/docker-security-advisory-docker-engine-authz-plugin/ although it requires AuthZ enabled

fix is already pushed to 24.x branch https://github.com/moby/moby/commit/852759a7df454cbf88db4e954c919becd48faa9b, but no new release yet.

Should we bump docker version to newer version or should we stick with 24.x for now?

**Comment by aclemons** [comment]
> fix is already pushed to 24.x branch [moby/moby@852759a](https://github.com/moby/moby/commit/852759a7df454cbf88db4e954c919becd48faa9b), but no new release yet.
> 
> Should we bump docker version to newer version or should we stick with 24.x for now?

https://endoflife.date/docker-engine

The supported releases seems unclear, but I feel like we'll get a 24.x tag. That said, I also fine if we upgrade to a newer version too. The CI runner triggered by sbo-bot currently needs work to run with 25.x and newer, but I manage my own packages for it and must eventually find a solution anyway.

**Comment by willysr** [comment]
> Docker Engine is supported by the [Moby Community](https://docs.docker.com/engine/install/#support), and as such - there’s no list of supported releases.

**Comment by willysr** [comment]
@aclemons can you review https://github.com/SlackBuildsOrg/slackbuilds/pull/7255 ?
