### ISSUE TITLE
automate build for sbo-bot

### ISSUE THREAD

**Issue by willysr** [SlackBuildsOrg/slackbuilds#7918]
@aclemons is it possible to automate run the build for sbo-bot ONLY for those PRs generated by automation scripts ?

**Comment by aclemons** [comment]
You mean the PRs opened https://github.com/aclemons/sbo-bot/blob/df95accdbcb0acb1269f0bde1084ddb80de411d5/bin/generate-submission-prs.sh#L1?

**Comment by willysr** [comment]
yes, since it's only us who can run that script so i assume it's safe to run the build directly

**Comment by aclemons** [comment]
Working on this now. Let me test it with the builds in pending. And then I'll let you try it

**Comment by aclemons** [comment]
Should be working now. Try it please on your next sync.

**Comment by willysr** [comment]
it still ask me whether we want to schedule a build for this. Is it possible to give the default value of YES for both questions so it will directly run the build?

**Comment by aclemons** [comment]
No, unfortunately not. We are queuing untrusted content - we *must* review the submission before we run it on the build server.
